# default 공통 설정
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true  # 콘솔에 sql 출력
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb